### ISSUE TITLE
Bug in the display of the grid

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/pdb-frontend#21]
How to reproduce: 

Navigate to X 4 Y 17 and then move one zone to the south. You should see a row of water disapear in the grid. I don't know what is the issue, frontend or backend.

There is also a problem of not being able to navigate to the last row of the map

**Comment by mrheaumeproulx** [comment]
After playing with the grid a little bit, I noticed that once when move down past the y position 10, the grids starts doing weird thing. 

The problem is mainly due to the array being unordered correctly. The source of the problem is the Collectors.groupingBy in the Grid controller.
`final Map<Integer, List<MapPoint>> mapPointsGrouped = mapPoints.stream().collect(Collectors.groupingBy(p -> p.getY()));` 

I don't know how it does the grouping and ordering, but the list has to be ordered from that point or after

**Comment by marcandregirard** [comment]
If it's around 10, then the translate I've done from ruby is not adequate since 10 is the size of the grid. probably the way I load things. I'll add some units tests to better pinpoint the problem :). Thanks for the info will make it easier to debug!

**Comment by mrheaumeproulx** [comment]
Logic wise, it works, In the front end you go through the array of arrays in order. Nothing is done front end to order or arrange things in a certain way. The front end expects the array of map points to be performatted once it receives it.

I ordered the list from the back end, and it resolved the problem, but it is the way we want to go?

**Comment by marcandregirard** [comment]
Yes the back end should handle the correct format and correct orders of things. Frontend should only modify things to fit things specifically on-screen or others things in the same vein. I opened the bug in this repo but it may not be best to fix it here. If I ever do a native or mobile first version, the data should be the same.

**Comment by marcandregirard** [comment]
It's fixed and should stay fixed :)
